import React, { useEffect, useState } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { FileText, Download, Printer, BarChart3, Users, Calendar, DollarSign } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

function Reports() {
  const [reportType, setReportType] = useState('employee');
  const [reportData, setReportData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [filters, setFilters] = useState({
    startDate: '',
    endDate: '',
    departmentId: '',
    employeeId: ''
  });
  const [departments, setDepartments] = useState([]);
  const [employees, setEmployees] = useState([]);
  const user = JSON.parse(localStorage.getItem('user') || '{}');

  useEffect(() => {
    fetchDepartments();
    fetchEmployees();
  }, []);

  useEffect(() => {
    if (reportType !== 'employee') {
      generateReport();
    }
  }, [reportType, filters]);

  const fetchDepartments = async () => {
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/departments', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDepartments(response.data);
    } catch (error) {
      toast.error('Failed to fetch departments');
    }
  };

  const fetchEmployees = async () => {
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/employees', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setEmployees(response.data);
    } catch (error) {
      toast.error('Failed to fetch employees');
    }
  };

  const generateReport = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    
    try {
      let data = [];
      
      switch(reportType) {
        case 'employee':
          const employeeResponse = await axios.get('/api/employees', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = employeeResponse.data;
          break;
          
        case 'attendance':
          let attendanceUrl = '/api/attendance/report';
          const params = new URLSearchParams();
          if (filters.startDate) params.append('start_date', filters.startDate);
          if (filters.endDate) params.append('end_date', filters.endDate);
          if (filters.employeeId) params.append('employee_id', filters.employeeId);
          if (params.toString()) attendanceUrl += `?${params.toString()}`;
          
          const attendanceResponse = await axios.get(attendanceUrl, {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = attendanceResponse.data;
          break;
          
        case 'payroll':
          const payrollResponse = await axios.get('/api/payroll', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = payrollResponse.data;
          break;
          
        case 'leave':
          const leaveResponse = await axios.get('/api/leaves', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = leaveResponse.data;
          break;
      }
      
      setReportData(data);
    } catch (error) {
      toast.error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const generateEmployeeReport = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/employees', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setReportData(response.data);
    } catch (error) {
      toast.error('Failed to generate employee report');
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Add title
    const title = getReportTitle();
    doc.setFontSize(18);
    doc.text(title, 14, 20);
    
    // Add generation date
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Generated by: ${user.username} (${user.role})`, 14, 36);
    
    // Prepare table data
    let tableData = [];
    let headers = [];
    
    switch(reportType) {
      case 'employee':
        headers = [['ID', '姓名', '职位', '部门', '邮箱', '电话', '薪资', '入职日期']];
        tableData = reportData.map(emp => [
          emp.employee_id,
          emp.full_name,
          emp.position,
          emp.department_name || 'N/A',
          emp.email,
          emp.phone,
          `$${emp.salary}`,
          new Date(emp.joining_date).toLocaleDateString()
        ]);
        break;
        
      case 'attendance':
        headers = [['员工', '职位', '日期', '上班时间', '下班时间', '状态']];
        tableData = reportData.map(att => [
          att.full_name,
          att.position,
          new Date(att.date).toLocaleDateString(),
          att.check_in,
          att.check_out || '-',
          att.status
        ]);
        break;
        
      case 'payroll':
        headers = [['员工', '职位', '基本薪资', '实发工资', '发放日期', '状态']];
        tableData = reportData.map(pay => [
          pay.full_name,
          pay.position,
          `$${pay.basic_salary}`,
          `$${pay.net_salary}`,
          new Date(pay.payment_date).toLocaleDateString(),
          pay.status
        ]);
        break;
        
      case 'leave':
        headers = [['员工', '职位', '请假类型', '开始日期', '结束日期', '状态']];
        tableData = reportData.map(leave => [
          leave.full_name,
          leave.position,
          leave.leave_type,
          new Date(leave.start_date).toLocaleDateString(),
          new Date(leave.end_date).toLocaleDateString(),
          leave.status
        ]);
        break;
    }
    
    // Add table to PDF
    doc.autoTable({
      head: headers,
      body: tableData,
      startY: 45,
      theme: 'striped',
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { top: 45 }
    });
    
    // Add summary
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.text(`Total Records: ${reportData.length}`, 14, finalY);
    
    // Save PDF
    doc.save(`${reportType}_report_${Date.now()}.pdf`);
    toast.success('PDF downloaded successfully');
  };

  const printReport = () => {
    const printWindow = window.open('', '_blank');
    const title = getReportTitle();
    
    let tableHTML = '';
    
    switch(reportType) {
      case 'employee':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>ID</th><th>姓名</th><th>职位</th><th>部门</th><th>邮箱</th><th>电话</th><th>薪资</th><th>入职日期</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(emp => `
                <tr>
                  <td>${emp.employee_id}</td>
                  <td>${emp.full_name}</td>
                  <td>${emp.position}</td>
                  <td>${emp.department_name || 'N/A'}</td>
                  <td>${emp.email}</td>
                  <td>${emp.phone}</td>
                  <td>$${emp.salary}</td>
                  <td>${new Date(emp.joining_date).toLocaleDateString()}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'attendance':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>员工</th><th>职位</th><th>日期</th><th>上班时间</th><th>下班时间</th><th>状态</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(att => `
                <tr>
                  <td>${att.full_name}</td>
                  <td>${att.position}</td>
                  <td>${new Date(att.date).toLocaleDateString()}</td>
                  <td>${att.check_in}</td>
                  <td>${att.check_out || '-'}</td>
                  <td>${att.status}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'payroll':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>员工</th><th>职位</th><th>基本薪资</th><th>实发工资</th><th>发放日期</th><th>状态</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(pay => `
                <tr>
                  <td>${pay.full_name}</td>
                  <td>${pay.position}</td>
                  <td>$${pay.basic_salary}</td>
                  <td>$${pay.net_salary}</td>
                  <td>${new Date(pay.payment_date).toLocaleDateString()}</td>
                  <td>${pay.status}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'leave':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>员工</th><th>职位</th><th>请假类型</th><th>开始日期</th><th>结束日期</th><th>状态</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(leave => `
                <tr>
                  <td>${leave.full_name}</td>
                  <td>${leave.position}</td>
                  <td>${leave.leave_type}</td>
                  <td>${new Date(leave.start_date).toLocaleDateString()}</td>
                  <td>${new Date(leave.end_date).toLocaleDateString()}</td>
                  <td>${leave.status}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
    }
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
          }
          h1 {
            color: #333;
            text-align: center;
          }
          .header {
            text-align: center;
            margin-bottom: 20px;
          }
          .info {
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
          }
          td {
            padding: 8px;
            border: 1px solid #ddd;
          }
          tr:nth-child(even) {
            background-color: #f2f2f2;
          }
          .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
        </div>
        <div class="info">
          <p>生成时间: ${new Date().toLocaleString()}</p>
          <p>生成人: ${user.username} (${user.role})</p>
          <p>总记录数: ${reportData.length}</p>
        </div>
        ${tableHTML}
        <div class="footer">
          <p>SmartTech Ltd - HR Management System</p>
        </div>
      </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.print();
    toast.success('Print job sent');
  };

  const getReportTitle = () => {
    const titles = {
      employee: '员工信息报表',
      attendance: '考勤报表',
      payroll: '薪资报表',
      leave: '请假报表'
    };
    return titles[reportType];
  };

  const getReportIcon = () => {
    const icons = {
      employee: <Users size={24} />,
      attendance: <Calendar size={24} />,
      payroll: <DollarSign size={24} />,
      leave: <FileText size={24} />
    };
    return icons[reportType];
  };

  const getReportSummary = () => {
    switch(reportType) {
      case 'employee':
        const totalSalary = reportData.reduce((sum, emp) => sum + parseFloat(emp.salary), 0);
        const avgSalary = totalSalary / (reportData.length || 1);
        return {
          title: '员工统计',
          metrics: [
            { label: '员工总数', value: reportData.length },
            { label: '总薪资支出', value: `$${totalSalary.toFixed(2)}` },
            { label: '平均薪资', value: `$${avgSalary.toFixed(2)}` },
            { label: '部门数量', value: departments.length }
          ]
        };
      case 'attendance':
        const present = reportData.filter(a => a.status === 'Present').length;
        const late = reportData.filter(a => a.status === 'Late').length;
        const absent = reportData.filter(a => a.status === 'Absent').length;
        return {
          title: '考勤统计',
          metrics: [
            { label: '出勤率', value: `${((present / (reportData.length || 1)) * 100).toFixed(1)}%` },
            { label: '正常出勤', value: present },
            { label: '迟到', value: late },
            { label: '缺勤', value: absent }
          ]
        };
      case 'payroll':
        const totalPaid = reportData.reduce((sum, pay) => sum + parseFloat(pay.net_salary), 0);
        return {
          title: '薪资统计',
          metrics: [
            { label: '薪资记录数', value: reportData.length },
            { label: '总发放金额', value: `$${totalPaid.toFixed(2)}` },
            { label: '平均薪资', value: `$${(totalPaid / (reportData.length || 1)).toFixed(2)}` },
            { label: '待处理记录', value: reportData.filter(p => p.status === 'Pending').length }
          ]
        };
      case 'leave':
        const approved = reportData.filter(l => l.status === 'Approved').length;
        const pending = reportData.filter(l => l.status === 'Pending').length;
        const rejected = reportData.filter(l => l.status === 'Rejected').length;
        return {
          title: '请假统计',
          metrics: [
            { label: '总申请数', value: reportData.length },
            { label: '已批准', value: approved },
            { label: '待审批', value: pending },
            { label: '已拒绝', value: rejected }
          ]
        };
      default:
        return { title: '统计', metrics: [] };
    }
  };

  const summary = getReportSummary();

  return (
    <div>
      <h1 className="text-3xl font-bold text-gray-800 mb-6">报表中心</h1>
      
      {/* Report Type Selector */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
        {['employee', 'attendance', 'payroll', 'leave'].map((type) => (
          <button
            key={type}
            onClick={() => {
              setReportType(type);
              if (type === 'employee') {
                generateEmployeeReport();
              }
            }}
            className={`p-4 rounded-lg shadow-md transition-all ${
              reportType === type 
                ? 'bg-blue-600 text-white' 
                : 'bg-white text-gray-700 hover:bg-gray-50'
            }`}
          >
            <div className="flex items-center gap-3">
              {type === 'employee' && <Users size={24} />}
              {type === 'attendance' && <Calendar size={24} />}
              {type === 'payroll' && <DollarSign size={24} />}
              {type === 'leave' && <FileText size={24} />}
              <div className="text-left">
                <div className="font-semibold">
                  {type === 'employee' && '员工报表'}
                  {type === 'attendance' && '考勤报表'}
                  {type === 'payroll' && '薪资报表'}
                  {type === 'leave' && '请假报表'}
                </div>
                <div className="text-sm opacity-75">查看详细报表</div>
              </div>
            </div>
          </button>
        ))}
      </div>

      {/* Filters for Attendance Report */}
      {reportType === 'attendance' && (
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">筛选条件</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">开始日期</label>
              <input
                type="date"
                value={filters.startDate}
                onChange={(e) => setFilters({ ...filters, startDate: e.target.value })}
                className="input-field"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">结束日期</label>
              <input
                type="date"
                value={filters.endDate}
                onChange={(e) => setFilters({ ...filters, endDate: e.target.value })}
                className="input-field"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">员工</label>
              <select
                value={filters.employeeId}
                onChange={(e) => setFilters({ ...filters, employeeId: e.target.value })}
                className="input-field"
              >
                <option value="">所有员工</option>
                {employees.map((emp) => (
                  <option key={emp.employee_id} value={emp.employee_id}>
                    {emp.full_name}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
      )}

      {/* Report Actions */}
      {reportData.length > 0 && (
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="flex justify-between items-center flex-wrap gap-4">
            <div className="flex items-center gap-3">
              {getReportIcon()}
              <div>
                <h2 className="text-xl font-semibold">{getReportTitle()}</h2>
                <p className="text-sm text-gray-600">共 {reportData.length} 条记录</p>
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={downloadPDF}
                className="btn-primary flex items-center gap-2"
              >
                <Download size={20} />
                下载 PDF
              </button>
              <button
                onClick={printReport}
                className="btn-secondary flex items-center gap-2"
              >
                <Printer size={20} />
                打印报表
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Statistics Summary */}
      {reportData.length > 0 && (
        <div className="bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg shadow-md p-6 mb-6 text-white">
          <h3 className="text-lg font-semibold mb-4">{summary.title}</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {summary.metrics.map((metric, index) => (
              <div key={index}>
                <p className="text-sm opacity-90">{metric.label}</p>
                <p className="text-2xl font-bold">{metric.value}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Report Table */}
      {loading ? (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">正在生成报表...</p>
        </div>
      ) : reportData.length > 0 ? (
        <div className="bg-white rounded-lg shadow overflow-x-auto">
          <table className="min-w-full">
            <thead className="bg-gray-50">
              <tr>
                {reportType === 'employee' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">姓名</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">职位</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">部门</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">邮箱</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">电话</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">薪资</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">入职日期</th>
                  </>
                )}
                {reportType === 'attendance' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">员工</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">职位</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">日期</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">上班时间</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">下班时间</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">状态</th>
                  </>
                )}
                {reportType === 'payroll' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">员工</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">职位</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">基本薪资</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">实发工资</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">发放日期</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">状态</th>
                  </>
                )}
                {reportType === 'leave' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">员工</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">职位</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">请假类型</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">开始日期</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">结束日期</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">状态</th>
                  </>
                )}
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportType === 'employee' && reportData.map((emp) => (
                <tr key={emp.employee_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.employee_id}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{emp.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.department_name || 'N/A'}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.email}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.phone}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${emp.salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {new Date(emp.joining_date).toLocaleDateString()}
                  </td>
                </tr>
              ))}
              {reportType === 'attendance' && reportData.map((att, idx) => (
                <tr key={idx}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{att.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {new Date(att.date).toLocaleDateString()}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.check_in}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.check_out || '-'}</td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      att.status === 'Present' ? 'bg-green-100 text-green-800' :
                      att.status === 'Late' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-red-100 text-red-800'
                    }`}>
                      {att.status}
                    </span>
                  </td>
                </tr>
              ))}
              {reportType === 'payroll' && reportData.map((pay) => (
                <tr key={pay.payroll_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{pay.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{pay.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${pay.basic_salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-green-600">${pay.net_salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {new Date(pay.payment_date).toLocaleDateString()}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      pay.status === 'Paid' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                    }`}>
                      {pay.status}
                    </span>
                  </td>
                </tr>
              ))}
              {reportType === 'leave' && reportData.map((leave) => (
                <tr key={leave.leave_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{leave.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{leave.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{leave.leave_type}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {new Date(leave.start_date).toLocaleDateString()}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {new Date(leave.end_date).toLocaleDateString()}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      leave.status === 'Approved' ? 'bg-green-100 text-green-800' :
                      leave.status === 'Rejected' ? 'bg-red-100 text-red-800' :
                      'bg-yellow-100 text-yellow-800'
                    }`}>
                      {leave.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <BarChart3 size={48} className="mx-auto text-gray-400 mb-4" />
          <p className="text-gray-500">点击生成报表查看数据</p>
        </div>
      )}
    </div>
  );
}

export default Reports;