import React, { useEffect, useState } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { FileText, Download, Printer, BarChart3, Users, Calendar, DollarSign } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

function Reports() {
  const [reportType, setReportType] = useState('employee');
  const [reportData, setReportData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [filters, setFilters] = useState({
    startDate: '',
    endDate: '',
    departmentId: '',
    employeeId: ''
  });
  const [departments, setDepartments] = useState([]);
  const [employees, setEmployees] = useState([]);
  const user = JSON.parse(localStorage.getItem('user') || '{}');

  useEffect(() => {
    fetchDepartments();
    fetchEmployees();
  }, []);

  useEffect(() => {
    if (reportType !== 'employee') {
      generateReport();
    }
  }, [reportType, filters]);

  const fetchDepartments = async () => {
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/departments', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDepartments(Array.isArray(response.data) ? response.data : []);
    } catch (error) {
      console.error('Failed to fetch departments:', error);
      toast.error('Failed to fetch departments');
      setDepartments([]);
    }
  };

  const fetchEmployees = async () => {
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/employees', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setEmployees(Array.isArray(response.data) ? response.data : []);
    } catch (error) {
      console.error('Failed to fetch employees:', error);
      toast.error('Failed to fetch employees');
      setEmployees([]);
    }
  };

  const generateReport = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    
    try {
      let data = [];
      
      switch(reportType) {
        case 'employee':
          const employeeResponse = await axios.get('/api/employees', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = Array.isArray(employeeResponse.data) ? employeeResponse.data : [];
          break;
          
        case 'attendance':
          let attendanceUrl = '/api/attendance/report';
          const params = new URLSearchParams();
          if (filters.startDate) params.append('start_date', filters.startDate);
          if (filters.endDate) params.append('end_date', filters.endDate);
          if (filters.employeeId) params.append('employee_id', filters.employeeId);
          if (params.toString()) attendanceUrl += `?${params.toString()}`;
          
          const attendanceResponse = await axios.get(attendanceUrl, {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = Array.isArray(attendanceResponse.data) ? attendanceResponse.data : [];
          break;
          
        case 'payroll':
          const payrollResponse = await axios.get('/api/payroll', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = Array.isArray(payrollResponse.data) ? payrollResponse.data : [];
          break;
          
        case 'leave':
          const leaveResponse = await axios.get('/api/leaves', {
            headers: { Authorization: `Bearer ${token}` }
          });
          data = Array.isArray(leaveResponse.data) ? leaveResponse.data : [];
          break;
      }
      
      setReportData(data);
    } catch (error) {
      console.error('Failed to generate report:', error);
      toast.error('Failed to generate report');
      setReportData([]);
    } finally {
      setLoading(false);
    }
  };

  const generateEmployeeReport = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    try {
      const response = await axios.get('/api/employees', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setReportData(Array.isArray(response.data) ? response.data : []);
    } catch (error) {
      console.error('Failed to generate employee report:', error);
      toast.error('Failed to generate employee report');
      setReportData([]);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!reportData || reportData.length === 0) {
      toast.error('No data to download');
      return;
    }

    const doc = new jsPDF();
    
    // Add title
    const title = getReportTitle();
    doc.setFontSize(18);
    doc.text(title, 14, 20);
    
    // Add generation date
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Generated by: ${user.username || 'Unknown'} (${user.role || 'Unknown'})`, 14, 36);
    
    // Prepare table data
    let tableData = [];
    let headers = [];
    
    switch(reportType) {
      case 'employee':
        headers = [['ID', 'Full Name', 'Position', 'Department', 'Email', 'Phone', 'Salary', 'Joining Date']];
        tableData = reportData.map(emp => [
          emp.employee_id || 'N/A',
          emp.full_name || 'N/A',
          emp.position || 'N/A',
          emp.department_name || 'N/A',
          emp.email || 'N/A',
          emp.phone || 'N/A',
          `$${emp.salary || 0}`,
          emp.joining_date ? new Date(emp.joining_date).toLocaleDateString() : 'N/A'
        ]);
        break;
        
      case 'attendance':
        headers = [['Employee', 'Position', 'Date', 'Check In', 'Check Out', 'Status']];
        tableData = reportData.map(att => [
          att.full_name || 'N/A',
          att.position || 'N/A',
          att.date ? new Date(att.date).toLocaleDateString() : 'N/A',
          att.check_in || 'N/A',
          att.check_out || '-',
          att.status || 'N/A'
        ]);
        break;
        
      case 'payroll':
        headers = [['Employee', 'Position', 'Basic Salary', 'Net Salary', 'Payment Date', 'Status']];
        tableData = reportData.map(pay => [
          pay.full_name || 'N/A',
          pay.position || 'N/A',
          `$${pay.basic_salary || 0}`,
          `$${pay.net_salary || 0}`,
          pay.payment_date ? new Date(pay.payment_date).toLocaleDateString() : 'N/A',
          pay.status || 'N/A'
        ]);
        break;
        
      case 'leave':
        headers = [['Employee', 'Position', 'Leave Type', 'Start Date', 'End Date', 'Status']];
        tableData = reportData.map(leave => [
          leave.full_name || 'N/A',
          leave.position || 'N/A',
          leave.leave_type || 'N/A',
          leave.start_date ? new Date(leave.start_date).toLocaleDateString() : 'N/A',
          leave.end_date ? new Date(leave.end_date).toLocaleDateString() : 'N/A',
          leave.status || 'N/A'
        ]);
        break;
    }
    
    // Add table to PDF
    doc.autoTable({
      head: headers,
      body: tableData,
      startY: 45,
      theme: 'striped',
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { top: 45 }
    });
    
    // Add summary
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.text(`Total Records: ${reportData.length}`, 14, finalY);
    
    // Save PDF
    doc.save(`${reportType}_report_${Date.now()}.pdf`);
    toast.success('PDF downloaded successfully');
  };

  const printReport = () => {
    if (!reportData || reportData.length === 0) {
      toast.error('No data to print');
      return;
    }

    const printWindow = window.open('', '_blank');
    const title = getReportTitle();
    
    let tableHTML = '';
    
    switch(reportType) {
      case 'employee':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>ID</th><th>Full Name</th><th>Position</th><th>Department</th><th>Email</th><th>Phone</th><th>Salary</th><th>Joining Date</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(emp => `
                <tr>
                  <td>${emp.employee_id || 'N/A'}</td>
                  <td>${emp.full_name || 'N/A'}</td>
                  <td>${emp.position || 'N/A'}</td>
                  <td>${emp.department_name || 'N/A'}</td>
                  <td>${emp.email || 'N/A'}</td>
                  <td>${emp.phone || 'N/A'}</td>
                  <td>$${emp.salary || 0}</td>
                  <td>${emp.joining_date ? new Date(emp.joining_date).toLocaleDateString() : 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'attendance':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>Employee</th><th>Position</th><th>Date</th><th>Check In</th><th>Check Out</th><th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(att => `
                <tr>
                  <td>${att.full_name || 'N/A'}</td>
                  <td>${att.position || 'N/A'}</td>
                  <td>${att.date ? new Date(att.date).toLocaleDateString() : 'N/A'}</td>
                  <td>${att.check_in || 'N/A'}</td>
                  <td>${att.check_out || '-'}</td>
                  <td>${att.status || 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'payroll':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>Employee</th><th>Position</th><th>Basic Salary</th><th>Net Salary</th><th>Payment Date</th><th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(pay => `
                <tr>
                  <td>${pay.full_name || 'N/A'}</td>
                  <td>${pay.position || 'N/A'}</td>
                  <td>$${pay.basic_salary || 0}</td>
                  <td>$${pay.net_salary || 0}</td>
                  <td>${pay.payment_date ? new Date(pay.payment_date).toLocaleDateString() : 'N/A'}</td>
                  <td>${pay.status || 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
        
      case 'leave':
        tableHTML = `
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <thead style="background-color: #4CAF50; color: white;">
              <tr>
                <th>Employee</th><th>Position</th><th>Leave Type</th><th>Start Date</th><th>End Date</th><th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${reportData.map(leave => `
                <tr>
                  <td>${leave.full_name || 'N/A'}</td>
                  <td>${leave.position || 'N/A'}</td>
                  <td>${leave.leave_type || 'N/A'}</td>
                  <td>${leave.start_date ? new Date(leave.start_date).toLocaleDateString() : 'N/A'}</td>
                  <td>${leave.end_date ? new Date(leave.end_date).toLocaleDateString() : 'N/A'}</td>
                  <td>${leave.status || 'N/A'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `;
        break;
    }
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
          }
          h1 {
            color: #333;
            text-align: center;
          }
          .header {
            text-align: center;
            margin-bottom: 20px;
          }
          .info {
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
          }
          td {
            padding: 8px;
            border: 1px solid #ddd;
          }
          tr:nth-child(even) {
            background-color: #f2f2f2;
          }
          .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
        </div>
        <div class="info">
          <p>Generated on: ${new Date().toLocaleString()}</p>
          <p>Generated by: ${user.username || 'Unknown'} (${user.role || 'Unknown'})</p>
          <p>Total Records: ${reportData.length}</p>
        </div>
        ${tableHTML}
        <div class="footer">
          <p>SmartTech Ltd - HR Management System</p>
        </div>
      </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.print();
    toast.success('Print job sent');
  };

  const getReportTitle = () => {
    const titles = {
      employee: 'Employee Report',
      attendance: 'Attendance Report',
      payroll: 'Payroll Report',
      leave: 'Leave Report'
    };
    return titles[reportType];
  };

  const getReportIcon = () => {
    const icons = {
      employee: <Users size={24} />,
      attendance: <Calendar size={24} />,
      payroll: <DollarSign size={24} />,
      leave: <FileText size={24} />
    };
    return icons[reportType];
  };

  const getReportSummary = () => {
    if (!reportData || reportData.length === 0) {
      return { title: 'Statistics', metrics: [] };
    }

    switch(reportType) {
      case 'employee':
        const totalSalary = reportData.reduce((sum, emp) => sum + (parseFloat(emp.salary) || 0), 0);
        const avgSalary = totalSalary / (reportData.length || 1);
        return {
          title: 'Employee Statistics',
          metrics: [
            { label: 'Total Employees', value: reportData.length },
            { label: 'Total Salary Expense', value: `$${totalSalary.toFixed(2)}` },
            { label: 'Average Salary', value: `$${avgSalary.toFixed(2)}` },
            { label: 'Total Departments', value: Array.isArray(departments) ? departments.length : 0 }
          ]
        };
      case 'attendance':
        const present = reportData.filter(a => a.status === 'Present').length;
        const late = reportData.filter(a => a.status === 'Late').length;
        const absent = reportData.filter(a => a.status === 'Absent').length;
        return {
          title: 'Attendance Statistics',
          metrics: [
            { label: 'Attendance Rate', value: `${((present / (reportData.length || 1)) * 100).toFixed(1)}%` },
            { label: 'Present', value: present },
            { label: 'Late', value: late },
            { label: 'Absent', value: absent }
          ]
        };
      case 'payroll':
        const totalPaid = reportData.reduce((sum, pay) => sum + (parseFloat(pay.net_salary) || 0), 0);
        return {
          title: 'Payroll Statistics',
          metrics: [
            { label: 'Total Payroll Records', value: reportData.length },
            { label: 'Total Amount Paid', value: `$${totalPaid.toFixed(2)}` },
            { label: 'Average Salary', value: `$${(totalPaid / (reportData.length || 1)).toFixed(2)}` },
            { label: 'Pending Records', value: reportData.filter(p => p.status === 'Pending').length }
          ]
        };
      case 'leave':
        const approved = reportData.filter(l => l.status === 'Approved').length;
        const pending = reportData.filter(l => l.status === 'Pending').length;
        const rejected = reportData.filter(l => l.status === 'Rejected').length;
        return {
          title: 'Leave Statistics',
          metrics: [
            { label: 'Total Requests', value: reportData.length },
            { label: 'Approved', value: approved },
            { label: 'Pending', value: pending },
            { label: 'Rejected', value: rejected }
          ]
        };
      default:
        return { title: 'Statistics', metrics: [] };
    }
  };

  const summary = getReportSummary();

  return (
    <div>
      <h1 className="text-3xl font-bold text-gray-800 mb-6">Report Center</h1>
      
      {/* Report Type Selector */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
        {['employee', 'attendance', 'payroll', 'leave'].map((type) => (
          <button
            key={type}
            onClick={() => {
              setReportType(type);
              if (type === 'employee') {
                generateEmployeeReport();
              } else {
                generateReport();
              }
            }}
            className={`p-4 rounded-lg shadow-md transition-all ${
              reportType === type 
                ? 'bg-blue-600 text-white' 
                : 'bg-white text-gray-700 hover:bg-gray-50'
            }`}
          >
            <div className="flex items-center gap-3">
              {type === 'employee' && <Users size={24} />}
              {type === 'attendance' && <Calendar size={24} />}
              {type === 'payroll' && <DollarSign size={24} />}
              {type === 'leave' && <FileText size={24} />}
              <div className="text-left">
                <div className="font-semibold">
                  {type === 'employee' && 'Employee Report'}
                  {type === 'attendance' && 'Attendance Report'}
                  {type === 'payroll' && 'Payroll Report'}
                  {type === 'leave' && 'Leave Report'}
                </div>
                <div className="text-sm opacity-75">View detailed report</div>
              </div>
            </div>
          </button>
        ))}
      </div>

      {/* Filters for Attendance Report */}
      {reportType === 'attendance' && (
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">Filter Criteria</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
              <input
                type="date"
                value={filters.startDate}
                onChange={(e) => setFilters({ ...filters, startDate: e.target.value })}
                className="input-field"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
              <input
                type="date"
                value={filters.endDate}
                onChange={(e) => setFilters({ ...filters, endDate: e.target.value })}
                className="input-field"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Employee</label>
              <select
                value={filters.employeeId}
                onChange={(e) => setFilters({ ...filters, employeeId: e.target.value })}
                className="input-field"
              >
                <option value="">All Employees</option>
                {Array.isArray(employees) && employees.map((emp) => (
                  <option key={emp.employee_id} value={emp.employee_id}>
                    {emp.full_name}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className="mt-4">
            <button onClick={generateReport} className="btn-primary">
              Apply Filters
            </button>
          </div>
        </div>
      )}

      {/* Report Actions */}
      {reportData.length > 0 && (
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="flex justify-between items-center flex-wrap gap-4">
            <div className="flex items-center gap-3">
              {getReportIcon()}
              <div>
                <h2 className="text-xl font-semibold">{getReportTitle()}</h2>
                <p className="text-sm text-gray-600">Total {reportData.length} records</p>
              </div>
            </div>
            <div className="flex gap-3">
              <button
                onClick={downloadPDF}
                className="btn-primary flex items-center gap-2"
              >
                <Download size={20} />
                Download PDF
              </button>
              <button
                onClick={printReport}
                className="btn-secondary flex items-center gap-2"
              >
                <Printer size={20} />
                Print Report
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Statistics Summary */}
      {reportData.length > 0 && summary.metrics.length > 0 && (
        <div className="bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg shadow-md p-6 mb-6 text-white">
          <h3 className="text-lg font-semibold mb-4">{summary.title}</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {summary.metrics.map((metric, index) => (
              <div key={index}>
                <p className="text-sm opacity-90">{metric.label}</p>
                <p className="text-2xl font-bold">{metric.value}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Report Table */}
      {loading ? (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Generating report...</p>
        </div>
      ) : reportData.length > 0 ? (
        <div className="bg-white rounded-lg shadow overflow-x-auto">
          <table className="min-w-full">
            <thead className="bg-gray-50">
              <tr>
                {reportType === 'employee' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Full Name</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Position</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Department</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Email</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Phone</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Salary</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Joining Date</th>
                  </>
                )}
                {reportType === 'attendance' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Employee</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Position</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Check In</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Check Out</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  </>
                )}
                {reportType === 'payroll' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Employee</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Position</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Basic Salary</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Net Salary</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Payment Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  </>
                )}
                {reportType === 'leave' && (
                  <>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Employee</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Position</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Leave Type</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Start Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">End Date</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  </>
                )}
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportType === 'employee' && reportData.map((emp) => (
                <tr key={emp.employee_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.employee_id}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{emp.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.department_name || 'N/A'}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.email}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emp.phone}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${emp.salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {emp.joining_date ? new Date(emp.joining_date).toLocaleDateString() : 'N/A'}
                  </td>
                </tr>
              ))}
              {reportType === 'attendance' && reportData.map((att, idx) => (
                <tr key={idx}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{att.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {att.date ? new Date(att.date).toLocaleDateString() : 'N/A'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.check_in}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{att.check_out || '-'}</td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      att.status === 'Present' ? 'bg-green-100 text-green-800' :
                      att.status === 'Late' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-red-100 text-red-800'
                    }`}>
                      {att.status}
                    </span>
                  </td>
                </tr>
              ))}
              {reportType === 'payroll' && reportData.map((pay) => (
                <tr key={pay.payroll_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{pay.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{pay.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">${pay.basic_salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-green-600">${pay.net_salary}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {pay.payment_date ? new Date(pay.payment_date).toLocaleDateString() : 'N/A'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      pay.status === 'Paid' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                    }`}>
                      {pay.status}
                    </span>
                  </td>
                </tr>
              ))}
              {reportType === 'leave' && reportData.map((leave) => (
                <tr key={leave.leave_id}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{leave.full_name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{leave.position}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{leave.leave_type}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {leave.start_date ? new Date(leave.start_date).toLocaleDateString() : 'N/A'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {leave.end_date ? new Date(leave.end_date).toLocaleDateString() : 'N/A'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 py-1 rounded-full text-xs ${
                      leave.status === 'Approved' ? 'bg-green-100 text-green-800' :
                      leave.status === 'Rejected' ? 'bg-red-100 text-red-800' :
                      'bg-yellow-100 text-yellow-800'
                    }`}>
                      {leave.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : !loading && (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <BarChart3 size={48} className="mx-auto text-gray-400 mb-4" />
          <p className="text-gray-500">Click generate report to view data</p>
        </div>
      )}
    </div>
  );
}

export default Reports;